name = "shineshop-site"
compatibility_date = "2025-06-05"
main = "workers-site/index.js"

# Specify the build output directory
pages_build_output_dir = ".next"

# Configure for Next.js App Router compatibility
compatibility_flags = ["nodejs_compat"]

# Set limits for proper RSC handling
limits = { cpu_ms = 50 }

# Environment variables
[env.production]
vars = { CF_PAGES = "1" }

# Site configuration
[site]
bucket = ".next" 