name = "shineshop-site"
compatibility_date = "2025-06-05"

# Specify the build output directory
pages_build_output_dir = ".next"

# Configure for Next.js App Router compatibility
compatibility_flags = ["nodejs_compat"]

# Set limits for proper RSC handling
limits = { cpu_ms = 50 }

# Build configuration
[build]
command = "npm run build"
output_directory = ".next"

# Environment variables
[env.production]
vars = { CF_PAGES = "1" } 