name = "shineshop-site"
compatibility_date = "2025-06-05"

[build]
command = "npm install --force && npm run build"
output_dir = ".next"

[site]
bucket = ".next"

# Required for Cloudflare Pages
pages_build_output_dir = ".next" 