name = "shineshop-site"
compatibility_date = "2025-06-05"

[build]
command = "npm run export"

# Configure Cloudflare Pages specifically
[site]
bucket = ".next"

# Required for Cloudflare Pages
[build.upload]
format = "directory"

[build_output]
directory = ".next"
include = ["**/*"] 