name = "shineshop-site"
compatibility_date = "2025-06-05"

# Specify the build output directory
pages_build_output_dir = "out"

# Configure for Next.js App Router compatibility
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production]
vars = { CF_PAGES = "1" } 