@echo off
echo Restoring from backup...
copy app\admin\dashboard\page.tsx.bak app\admin\dashboard\page.tsx /Y

echo Updating file content...
echo Replacing lines...
powershell -ExecutionPolicy Bypass -Command "(Get-Content app\admin\dashboard\page.tsx) -replace 'const \[showNotification, setShowNotification\] = useState\(false\)', 'const [showSavedNotification, setShowSavedNotification] = useState(false)' | Set-Content app\admin\dashboard\page.tsx"

echo Fixing duplicate declaration...
powershell -ExecutionPolicy Bypass -Command "(Get-Content app\admin\dashboard\page.tsx) -replace '// Add showSavedNotification state back[\r\n]+[\t ]*const \[showSavedNotification, setShowSavedNotification\] = useState\(false\)', '' | Set-Content app\admin\dashboard\page.tsx"

echo Starting development server...
npm run dev 